<?php


/**
 * Implements hook_form_alter().
 */
function webform_node_value_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'webform_configure_form') {
    webform_node_value_configuration_form($form);
  }

  // Form has a Webform.
  if (isset($form['#node']->webform)) {

    // Webform is being presented to visitor.
    if (!isset($form['#node_edit_form'])) {
      // Important to add it to start of the list, before Webform's submit function sends the email.
      array_unshift($form['#submit'], 'webform_node_value_client_submit');
    }

  }
}

/**
 * Add our configuration options to the Webform settings form.
 */
function webform_node_value_configuration_form(&$form) {

  $settings = webform_node_value_configuration_get($form['nid']['#value']);

  $form['webform_node_value'] = array(
    '#type'        => 'fieldset',
    '#tree'        => TRUE,
    '#title'       => t('Set Value From A Node'),
    '#description' => t('Fill a Webform field with the value of a node field.'),
    '#collapsible' => TRUE,
    '#collapsed'   => TRUE,
  );

  $form['webform_node_value']['prefix'] = array(
    '#type'          => 'textfield',
    '#required'      => FALSE,
    '#title'         => t('Path Alias Prefix'),
    '#description'   => t("Add a prefix to the path alias of the node, if necessary, e.g. 'sector/'"),
    '#default_value' => isset($settings->prefix) ? $settings->prefix : '',
  );

  $form['webform_node_value']['webform_source'] = array(
    '#type'          => 'textfield',
    '#required'      => FALSE,
    '#title'         => t('Webform Source Field'),
    '#description'   => t("Webform field who's value (key) will be used as a path to the node, e.g. 'airline'"),
    '#default_value' => isset($settings->webform_source) ? $settings->webform_source : '',
  );

  $form['webform_node_value']['node_field_name'] = array(
    '#type'          => 'textfield',
    '#required'      => FALSE,
    '#title'         => t('Node Source Field'),
    '#description'   => t("Node field to get a value from, e.g. 'field_sector_contact_email'"),
    '#default_value' => isset($settings->node_field_name) ? $settings->node_field_name : '',
  );

  $form['webform_node_value']['webform_destination'] = array(
    '#type'          => 'textfield',
    '#required'      => FALSE,
    '#title'         => t('Webform Target Field'),
    '#description'   => t("Webform field to put value from node into, e.g. 'send_to_email'"),
    '#default_value' => isset($settings->webform_destination) ? $settings->webform_destination : '',
  );

  array_unshift($form['#submit'], 'webform_node_value_configuration_submit');
}

function webform_node_value_configuration_submit($form, &$form_state) {
  $settings = $form_state['values']['webform_node_value'];
  $settings['nid'] = $form_state['values']['nid'];
  webform_node_value_configuration_save($settings);

  return;
}

/**
 * Submit callback for the client form.
 * Fetch node field value and insert it in Webform field.
 *
 * @param $form
 * @param $form_state
 */
function webform_node_value_client_submit($form, &$form_state) {
  $settings = webform_node_value_configuration_get($form_state['values']['details']['nid']);

  if (!isset($form_state['input']['submitted'][$settings->webform_source])) {
    watchdog('webform_node_value', t('Source field not found on Webform.'));
    return;
  }

  $webform_value = $form_state['input']['submitted'][$settings->webform_source];
  $node_alias_path = ltrim($settings->prefix . $webform_value, '/');
  $node_system_path = drupal_get_normal_path($node_alias_path);

  // No node system path found.
  if ($node_alias_path == $node_system_path) {
    watchdog('webform_node_value', t('System path not found.'));
    return;
  }

  $path_parts = explode('/', $node_system_path);

  if ($path_parts[0] != 'node' || !is_numeric($path_parts[1])) {
    watchdog('webform_node_value', t('Node not found.'));
    return;
  }

  $nid = $path_parts[1];

  // Get node field info.
  $node = node_load($nid);
  $node_field = field_get_items('node', $node, $settings->node_field_name);
  $node_field_value = field_view_value('node', $node, $settings->node_field_name, $node_field[0]);

  // Set value of field in Webform with value from node.
  $form_state['values']['submitted'][$settings->webform_destination] = render($node_field_value);

  return;
}

function webform_node_value_configuration_save($settings) {

  db_delete('webform_node_value')
    ->condition('nid', $settings['nid'])
    ->execute();

  if (!empty($settings['webform_source'])) {
    db_insert('webform_node_value')
      ->fields($settings)
      ->execute();
  }

}

function webform_node_value_configuration_get($nid) {
  $configuration = db_query_range('SELECT * FROM {webform_node_value} WHERE nid = :nid', 0, 1, array(':nid' => $nid))->fetchObject();
  return $configuration;
}
