<?php
/**
 * @file
 * service_portal_search.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function service_portal_search_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_excluded_extensions';
  $strongarm->value = 'aif art avi bmp gif ico jpg mov mp3 mp4 mpg oga ogv png psd ra ram rgb tif wmv';
  $export['apachesolr_attachments_excluded_extensions'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_excluded_mime';
  $strongarm->value = array(
    'audio/x-aiff' => 1,
    'image/x-jg' => 1,
    'video/x-msvideo' => 1,
    'image/x-ms-bmp' => 1,
    'image/gif' => 1,
    'image/vnd.microsoft.icon' => 1,
    'image/jpeg' => 1,
    'video/quicktime' => 1,
    'audio/mpeg' => 1,
    'video/mp4' => 1,
    'video/mpeg' => 1,
    'audio/ogg' => 1,
    'video/ogg' => 1,
    'image/png' => 1,
    'image/x-photoshop' => 1,
    'audio/x-realaudio' => 1,
    'audio/x-pn-realaudio' => 1,
    'image/x-rgb' => 1,
    'image/tiff' => 1,
    'video/x-ms-wmv' => 1,
  );
  $export['apachesolr_attachments_excluded_mime'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_extract_using';
  $strongarm->value = 'tika';
  $export['apachesolr_attachments_extract_using'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_tika_jar';
  $strongarm->value = 'tika-app-1.2.jar';
  $export['apachesolr_attachments_tika_jar'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_attachments_tika_path';
  $strongarm->value = '/opt/apache-solr-3.6.1/lib';
  $export['apachesolr_attachments_tika_path'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_default_environment';
  $strongarm->value = 'solr';
  $export['apachesolr_default_environment'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_index_last';
  $strongarm->value = array(
    'solr' => array(
      'comment' => array(
        'last_changed' => 0,
        'last_entity_id' => 0,
      ),
      'i18n_translation' => array(
        'last_changed' => 0,
        'last_entity_id' => 0,
      ),
      'node' => array(
        'last_changed' => '1365408064',
        'last_entity_id' => '121',
      ),
      'file' => array(
        'last_changed' => '1360560342',
        'last_entity_id' => '47',
      ),
      'taxonomy_term' => array(
        'last_changed' => 0,
        'last_entity_id' => 0,
      ),
      'taxonomy_vocabulary' => array(
        'last_changed' => 0,
        'last_entity_id' => 0,
      ),
      'user' => array(
        'last_changed' => 0,
        'last_entity_id' => 0,
      ),
      'rules_config' => array(
        'last_changed' => 0,
        'last_entity_id' => 0,
      ),
    ),
  );
  $export['apachesolr_index_last'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_index_updated';
  $strongarm->value = array(
    'solr' => 1365495843,
  );
  $export['apachesolr_index_updated'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_last_optimize';
  $strongarm->value = 1365483242;
  $export['apachesolr_last_optimize'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_multisitesearch_last_metadata_update';
  $strongarm->value = 1365493264;
  $export['apachesolr_multisitesearch_last_metadata_update'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_multisitesearch_metadata';
  $strongarm->value = array(
    'ki9kp1' => array(
      'id' => 'ki9kp1/multisite.metadata/1',
      'site' => 'http://landisgyr.cn.capgemini.com/zh-hans',
      'hash' => 'ki9kp1',
      'entity_id' => 1,
      'entity_type' => 'multisite.meta',
      'ss_multisite_meta_sitename' => 'landisgyr.cn.capgemini.com',
      'timestamp' => '2013-04-09T07:41:04.847Z',
      'sm_multisite_meta_taxonomy' => array(
        0 => 'Forums',
        1 => 'Tags',
      ),
      'sm_multisite_meta_bundles' => array(
        0 => 'Article',
        1 => 'Basic page',
        2 => '手册页',
        3 => '文件',
      ),
    ),
    '4p1tde' => array(
      'id' => '4p1tde/multisite.metadata/1',
      'site' => 'http://service-portal.cn.capgemini.com/',
      'hash' => '4p1tde',
      'entity_id' => 1,
      'entity_type' => 'multisite.meta',
      'ss_multisite_meta_sitename' => 'Service Portal',
      'timestamp' => '2013-04-09T08:13:05.759Z',
      'sm_multisite_meta_taxonomy' => array(
        0 => 'Tags',
      ),
      'sm_multisite_meta_bundles' => array(
        0 => 'Article',
        1 => 'Basic page',
        2 => 'File',
      ),
    ),
  );
  $export['apachesolr_multisitesearch_metadata'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_search_mlt_blocks';
  $strongarm->value = array(
    'mlt-001' => array(
      'name' => 'More like this',
      'num_results' => '5',
      'mlt_fl' => array(
        'label' => 'label',
        'taxonomy_names' => 'taxonomy_names',
      ),
      'mlt_env_id' => 'solr',
      'mlt_mintf' => '1',
      'mlt_mindf' => '1',
      'mlt_minwl' => '3',
      'mlt_maxwl' => '15',
      'mlt_maxqt' => '20',
      'mlt_type_filters' => array(),
      'mlt_custom_filters' => '',
      'delta' => 'mlt-001',
    ),
  );
  $export['apachesolr_search_mlt_blocks'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'apachesolr_site_hash';
  $strongarm->value = 'ki9kp1';
  $export['apachesolr_site_hash'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'facetapi:block_cache:apachesolr@solr';
  $strongarm->value = '-1';
  $export['facetapi:block_cache:apachesolr@solr'] = $strongarm;

  return $export;
}
